/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fundamentals;

import java.util.Arrays;

public class Library {
    //loop through n times and out a number in the array each time
// make each  number random between 1-6
    public static int[] roll(int n) {
        int[] diceRoll = new int[n];
        for (int i = 0; i < diceRoll.length; i++) {
            diceRoll[i] = (int) (Math.random() * 6);
        }

        return diceRoll;
    }
}

//    public static boolean containsDuplicates(int[] arr){
//// random array of numbers and need to know if there are any repeats
//// loop through an array and look for duplicates
//    }
//}


// sum and divide - calculate averages

// 