/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fundamentals;

import fundamentals.Library;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        int[] test = classUnderTest.roll(3);
        int temp = test.length;

        assertEquals(3, temp);
    }
    @Test public void testcontainsDuplicates() {
        int[] arr = {1,2,3,1};
        boolean output = Library.containsDuplicates(arr);
        assertTrue(output);
    }
}

