/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafundamentals;

public class Library {

    public static int[] roll(int n) {
        int[] diceRoll = new int[n];
//loop through n times and out a number in the array each time
// make each  number random between 1-6
        return diceRoll;
    }
    public static boolean containsDuplicates(int[] arr){
// random array of numbers and need to know if there are any repeats
// loop through an array and look for duplicates
    }
}


// sum and divide - calculate averages

// 